# Generated by Django 5.0.6 on 2025-11-08 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IA',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modele', models.CharField(max_length=255)),
                ('seuil_confiance', models.FloatField(default=0.5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='En cours', max_length=50)),
                ('priority', models.CharField(default='Moyenne', max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('manager', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='projects.fournisseur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('MAITRE_OUVRAGE', 'MaitreOuvrage'), ('CHEF_DE_PROJET', 'ChefDeProjet'), ('MEMBRE_TECHNIQUE', 'MembreTechnique')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='projects.chantier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chantier',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='projects.projet'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant_prev', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_depense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='projects.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=16)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='NOUVELLE', max_length=50)),
                ('ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='projects.ia')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='projects.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='projects.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RessourceHumaine',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.ressource')),
                ('role', models.CharField(max_length=255)),
                ('competence', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('projects.ressource',),
        ),
        migrations.CreateModel(
            name='RessourceMaterielle',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.ressource')),
                ('type', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('projects.ressource',),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('progress', models.FloatField(default=0)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projects.lot')),
                ('ressources', models.ManyToManyField(blank=True, related_name='taches', to='projects.ressource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
