# Generated by Django 4.2.7 on 2025-11-01 17:17
# Modified to handle bigint to uuid conversion

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_utilisateur_is_active_utilisateur_is_approved'),
    ]

    operations = [
        # Use RunSQL for the conversion
        migrations.RunSQL(
            sql=[
                # Delete all IA objects and related alertes (safe for new deployment)
                "DELETE FROM projects_alerte WHERE ia_id IS NOT NULL;",
                "DELETE FROM projects_ia;",
                # Drop foreign key constraint from Alerte to IA
                "ALTER TABLE projects_alerte DROP CONSTRAINT IF EXISTS projects_alerte_ia_id_fkey;",
                # Drop the primary key constraint
                "ALTER TABLE projects_ia DROP CONSTRAINT IF EXISTS projects_ia_pkey;",
                # Drop the old id column
                "ALTER TABLE projects_ia DROP COLUMN IF EXISTS id;",
                # Add new UUID id column
                "ALTER TABLE projects_ia ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid();",
                # Change ia_id column type in projects_alerte to UUID
                "ALTER TABLE projects_alerte DROP COLUMN IF EXISTS ia_id;",
                "ALTER TABLE projects_alerte ADD COLUMN ia_id UUID REFERENCES projects_ia(id) ON DELETE SET NULL;",
            ],
            reverse_sql=[
                "DELETE FROM projects_ia;",
                "ALTER TABLE projects_alerte DROP CONSTRAINT IF EXISTS projects_alerte_ia_id_fkey;",
                "ALTER TABLE projects_alerte DROP COLUMN IF EXISTS ia_id;",
                "ALTER TABLE projects_ia DROP CONSTRAINT IF EXISTS projects_ia_pkey;",
                "ALTER TABLE projects_ia DROP COLUMN IF EXISTS id;",
                "ALTER TABLE projects_ia ADD COLUMN id BIGSERIAL PRIMARY KEY;",
                "ALTER TABLE projects_alerte ADD COLUMN ia_id BIGINT REFERENCES projects_ia(id) ON DELETE SET NULL;",
            ],
        ),
        # Update the model state to reflect the change
        migrations.AlterField(
            model_name='ia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
