# Generated by Django 4.2.7 on 2025-11-01 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_utilisateur_is_active_utilisateur_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
