# Generated by Django 4.2.7 on 2025-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_ia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
